### ISSUE TITLE
Multiple functions support ?

### ISSUE THREAD

**Issue by gaetschwartz** [invertase/dart_edge#23]
I've browsed around but I'm not sure to understand how it is intended to be used to use multiple functions. Do we need one dart project for each function ?

**Comment by Salakar** [comment]
You could use a monorepo with a tool like https://github.com/invertase/melos; each function could be a private package in ./packages for example. You can easily share local dependencies and build/deploy scripts with Melos too.

**Comment by gaetschwartz** [comment]
But AFAIK when using `edge build supabase_functions --dev` it always builds it as `supabase/functions/dart-edge` ?

**Comment by Ehesp** [comment]
Yeah thus was part of my thinking for https://github.com/invertase/dart_edge/issues/12

You can define entrypoints -> name. I'll have a think.

**Comment by gaetschwartz** [comment]
DM'd you on Twitter about that :) @Ehesp

**Comment by MichealReed** [comment]
My workflow looks like --

1. Create new function with `edge new supabase_functions example_dart`
2. cd example_dart && build supabase_functions --dev
3. rename example_dart/supabase/functions/dart_edge to example_dartgen
4. move example_dartgen to parent supabase/functions, next to original example_dart

So my folder looks like:
```
-supabase
 -functions
  -example_dart
  -example_dartgen
  -packages
```

Seems to be working well for organizes so far, maybe it will help others manage multiple functions.

**Comment by point-source** [comment]
I also am having issues using this with multiple functions. Ideally, I think I'd like to have a mirrored folder structure. Basically `/edge/functions/[my_function_name]` of which there can be N functions and then once `edge build supabase_functions` is called, it builds each function in `/edge/functions/` and outputs to `/supabase/functions/*`.

Alternatively, if the `edge build supabase_functions` accepted input/output args, I could make this behavior myself.

Currently, this tool seems to assume it will manage the entire dart package. This is not necessarily the case since sometimes your package includes multiple aspect of your backend and sometimes even your frontend (as is often the case with supabase + frontend in one repo)
